services:
  - type: web
    name: hospital-risk-platform
    env: docker
    dockerfilePath: 06-cicd/frontend/Dockerfile
    dockerContext: 06-cicd/frontend
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: ML_API_URL
        value: https://hospital-readmission-risk-predictor-pcv7.onrender.com
