[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:ml-api]
command=uvicorn app:app --host 0.0.0.0 --port 8080
directory=/app/backend
environment=PORT="8080",DISABLE_SHAP="true"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true

[program:frontend]
command=node server/src/index.js
directory=/app/frontend
environment=PORT="7860",ML_API_URL="http://localhost:8080",NODE_ENV="production",CLIENT_ORIGIN="*"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true
