version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ML_API_URL=https://hospital-readmission-risk-predictor-pcv7.onrender.com
    restart: unless-stopped
